project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
  resources:
    - files/Hieu_Duong_CV.pdf
website:
  title: "Hieu Duong"
  favicon: favicon-arch.svg
  navbar:
    background: light
    right:
      - text: "Posts"
        file: posts.qmd
      - text: "Life"
        file: life.qmd
      - text: "Books"
        file: books.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc-location: left



