project:
  type: website
  output-dir: docs
website:
  title: "Hieu Duong"
  navbar:
    background: light
    right:
      - icon: github
        href: https://github.com/hieudx149
      - icon: linkedin
        href: https://www.linkedin.com/in/hieu-duong-b55018165/
      - icon: facebook
        href: https://www.facebook.com/xhd99
    left: 
      - text: "About"
        file: index.qmd
      - text: "Posts"
        file: posts.qmd
      - text: "Tiếng Việt"
        file: vi_posts.qmd
format:
  html:
    theme: cosmo
    css: styles.css



